Polish translation (pl_PL)
GTNewHorizons/SpiceOfLife pull request #33
Opened 2024-01-14 23:09 UTC by Mpcs

Strings for two tooltip values are not in the lang file, so i'm not sure how to translate them:
![obraz](https://github.com/GTNewHorizons/SpiceOfLife/assets/20343738/0d7da4e8-7f20-4f4a-9d56-fd2c98cb7ea8)
But other than that, the whole mod is translated now :)

2024-01-16 17:47 UTC, Pxx500 requested changes

2024-01-16 17:47 UTC, Pxx500 commented on src/main/resources/assets/spiceoflife/lang/pl_PL.lang
> +spiceoflife.tooltip.not.eaten.ever=Jeszcze nie jedzone! Jak może smakować?
Ciekawe jak smakuje? może brzmieć lepiej

2024-01-16 17:47 UTC, Pxx500 commented on src/main/resources/assets/spiceoflife/lang/pl_PL.lang
> +spiceoflife.gui.expires.in.food=Wygasa po zjedzeniu dowolnego jedzenia jeszcze %s %s
dwa razy "%s" jest umyślne?

2024-01-16 17:52 UTC, Mpcs commented on src/main/resources/assets/spiceoflife/lang/pl_PL.lang
> +spiceoflife.gui.alltime.food.eaten=Ilość zjedzonego jedzenia kiedykolwiek
O super, jakoś głowiłem się i nic lepszego nie mogłem wymyślić haha

2024-01-16 17:52 UTC, Mpcs commented on src/main/resources/assets/spiceoflife/lang/pl_PL.lang
> +spiceoflife.tooltip.not.eaten.ever=Jeszcze nie jedzone! Jak może smakować?
Zmienię

2024-01-16 17:57 UTC, Pxx500 commented on src/main/resources/assets/spiceoflife/lang/pl_PL.lang
> +spiceoflife.gui.alltime.food.eaten=Ilość zjedzonego jedzenia kiedykolwiek
napisz ChatGPT: Sparafrazuj "..."
i rerolluj aż wypluje coś co da się przeczytać bez zdziwienia na twarzy

2024-01-21 09:54 UTC, Dream-Master commented
@Mpcs can you add the changes pxx requested ?

2024-01-21 10:53 UTC, Mpcs commented
Yes, i was just a bit busy this week, I'll take care of both of the issues soon

2024-01-23 20:08 UTC, Mpcs commented
Done

2024-01-23 21:51 UTC, Pxx500 approved these changes
Looks good, well done

2024-01-24 09:07 UTC, merged